ServicioSocialFS/core/views.py
# core/views.py

from flask import render_template, request, Blueprint

core = Blueprint('core', __name__)

@core.route('/')
def index():
    return render_template('index.html')
    

# @core.route('/about')
# def about():
#     return render_template('about.html')

ServicioSocialFS/services/views.py
# services/views.py
from flask_login import current_user, login_required
from flask import render_template,url_for,flash, redirect,request,Blueprint
from ServicioSocialFS.services.forms import FichaForm
from ServicioSocialFS.models import DatosPersonales, Procedencia, Residencia, DatosAcademicos, DatosPadre, DatosMadre, SituacionFamiliar,User
from ServicioSocialFS import db

services = Blueprint('services',__name__)

@services.route("/formulario_ingresante", methods=['GET', 'POST'])
#@login_required
def form_ingresante():
    form = FichaForm()
    if (request.method == 'POST') or (form.validate_on_submit()):
        dper = DatosPersonales(
            codigo_matricula = form.dper_codigo_matricula.data,
            carrera = form.dper_carrera.data,
            facultad = form.dper_facultad.data,
            apellido_pa = form.dper_apellido_pa.data,
            apellido_ma = form.dper_apellido_ma.data,
            nombre = form.dper_nombre.data,
            dni = form.dper_dni.data,
            discapacitado = form.dper_discapacitado.data,
            estado_civil = form.dper_estado_civil.data,
            email = form.dper_email.data,
            celular = form.dper_celular.data
        )
        db.session.add(dper)
        db.session.commit()

        dpro = Procedencia(
            pais = form.dpro_pais.data,
            departamento = form.dpro_departamento.data,
            provincia = form.dpro_provincia.data,
            distrito = form.dpro_distrito.data,
            tipo_vivienda = form.dpro_tipo_vivienda.data,
            material_vivienda = form.dpro_material_vivienda.data,
            num_habitaciones = form.dpro_num_habitaciones.data,
            zona_rural = form.dpro_zona_rural.data,
            barrio = form.dpro_barrio.data,
            direccion = form.dpro_direccion.data,
            luz_electrica = form.dpro_luz_electrica.data,
            agua_potable = form.dpro_agua_potable.data,
            desague = form.dpro_desague.data,
            telefono_fijo = form.dpro_telefono_fijo.data,
            internet = form.dpro_internet.data,
            television_cable = form.dpro_television_cable.data,
            radio = form.dpro_radio.data
        )
        db.session.add(dpro)
        db.session.commit()
        
        dres = Residencia(
            pais = form.dres_pais.data,
            departamento = form.dres_departamento.data,
            provincia = form.dres_provincia.data,
            distrito = form.dres_distrito.data,
            tipo_vivienda = form.dres_tipo_vivienda.data,
            material_vivienda = form.dres_material_vivienda.data,
            num_habitaciones = form.dres_num_habitaciones.data,
            zona_rural = form.dres_zona_rural.data,
            barrio = form.dres_barrio.data,
            direccion = form.dres_direccion.data,
            referencia = form.dres_referencia.data,
            luz_electrica = form.dres_luz_electrica.data,
            agua_potable = form.dres_agua_potable.data,
            desague = form.dres_desague.data,
            telefono_fijo = form.dres_telefono_fijo.data,
            internet = form.dres_internet.data,
            television_cable = form.dres_television_cable.data,
            radio = form.dres_radio.data
        )
        db.session.add(dres)
        db.session.commit()

        daca = DatosAcademicos(
            colegio = form.daca_colegio.data,
            ano_culminacion_estudio = form.daca_ano_culminacion_estudio.data,
            num_postulacion =  form.daca_num_postulacion.data,
            otra_carrera = form.daca_otra_carrera.data,
            tipo_preparacion = form.daca_tipo_preparacion.data,
            motivo_postulacion = form.daca_motivo_postulacion.data,
            escuela_motivo = form.daca_escuela_motivo.data
        )
        db.session.add(daca)
        db.session.commit()

        dpad = DatosPadre(
            apellido_pa = form.dpad_apellido_pa.data,
            apellido_ma = form.dpad_apellido_ma.data,
            nombre = form.dpad_nombre.data,
            esta_vivo = form.dpad_esta_vivo.data,
            estado_civil = form.dpad_estado_civil.data,
            nivel_educacion = form.dpad_nivel_educacion.data,
            fecha_nacimiento =  form.dpad_fecha_nacimiento.data,
            pais = form.dpad_pais.data,
            departamento = form.dpad_departamento.data,
            provincia = form.dpad_provincia.data,
            distrito = form.dpad_distrito.data,
            zona_rural = form.dpad_zona_rural.data,
            discapacidad_trabajo =  form.dpad_discapacidad_trabajo.data,
            primera_ocupacion = form.dpad_primera_ocupacion.data,
            segunda_ocupacion = form.dpad_segunda_ocupacion.data,
            ingresos = form.dpad_ingresos.data
        )
        db.session.add(dpad)
        db.session.commit()

        dmad = DatosMadre(
            apellido_pa = form.dmad_apellido_pa.data,
            apellido_ma = form.dmad_apellido_ma.data,
            nombre = form.dmad_nombre.data,
            esta_vivo = form.dmad_esta_vivo.data,
            estado_civil = form.dmad_estado_civil.data,
            nivel_educacion = form.dmad_nivel_educacion.data,
            fecha_nacimiento =  form.dmad_fecha_nacimiento.data,
            pais = form.dmad_pais.data,
            departamento = form.dmad_departamento.data,
            provincia = form.dmad_provincia.data,
            distrito = form.dmad_distrito.data,
            zona_rural = form.dmad_zona_rural.data,
            discapacidad_trabajo =  form.dmad_discapacidad_trabajo.data,
            primera_ocupacion = form.dmad_primera_ocupacion.data,
            segunda_ocupacion = form.dmad_segunda_ocupacion.data,
            ingresos = form.dmad_ingresos.data
        )
        db.session.add(dmad)
        db.session.commit()

        sfam = SituacionFamiliar(
            dependencia_padre = form.sfam_dependencia_padre.data,
            dependencia_madre = form.sfam_dependencia_madre.data,
            dependencia_hermanos = form.sfam_dependencia_hermanos.data,
            dependencia_conyuge = form.sfam_dependencia_conyuge.data,
            dependencia_pariente = form.sfam_dependencia_pariente.data,
            autosostenimiento = form.sfam_autosostenimiento.data,
            vive_con = form.sfam_vive_con.data,
            contacto_nombre = form.sfam_contacto_nombre.data,
            contacto_parentesco =  form.sfam_contacto_parentesco.data,
            contacto_direccion = form.sfam_contacto_direccion.data,
            contacto_lugar = form.sfam_contacto_lugar.data,
            contacto_celular = form.sfam_contacto_celular.data
        )
        db.session.add(sfam)
        db.session.commit()
        
        user = User(
            codigo = form.dper_codigo_matricula.data,
            password_hash = form.user_password.data,
            datos_personales_id = dper.id,
            procedencia_id = dpro.id,
            residencia_id = dres.id,
            situacion_familiar_id = sfam.id,
            datos_madre_id = dmad.id,
            datos_padre_id = dpad.id,
            datos_academicos_id = daca.id
        )
        db.session.add(user)
        db.session.commit()
        print('Done')
        return redirect(url_for('core.index'))
    else:
        print('pass qweqwe')
    return render_template('ficha_formulario.html', form=form)

@services.route("/pagina_administrador")
@login_required
def admin_page():
    val = current_user.codigo
    print(val)
    return render_template('administrador.html', val=val)

@services.route("/registra_estudiante")
@login_required
def regist_est():
    val = current_user.codigo
    print(val)
    return render_template('registra_estudiante.html', val=val)

##############################################################################

@services.route("/datos_personales")
@login_required
def datos_personales():
    dper = DatosPersonales.query.filter_by(id=current_user.datos_personales_id).first()
    print(dper)
    return render_template('ficha_dper.html', dper=dper)

@services.route("/datos_procedencia")
@login_required
def datos_procedencia():
    dpro = Procedencia.query.filter_by(id=current_user.procedencia_id).first()
    
    return render_template('ficha_dpro.html', dpro=dpro)

@services.route("/datos_residencia")
@login_required
def datos_residencia():
    dres = Residencia.query.filter_by(id=current_user.residencia_id).first()
    
    return render_template('ficha_dres.html', dres=dres)

@services.route("/datos_academicos")
@login_required
def datos_academicos():
    daca = DatosAcademicos.query.filter_by(id=current_user.datos_academicos_id).first()
    
    return render_template('ficha_daca.html', daca=daca)

@services.route("/datos_padre")
@login_required
def datos_padre():
    dpad = DatosPadre.query.filter_by(id=current_user.datos_padre_id).first()
    
    return render_template('ficha_dpad.html', dpad=dpad)

@services.route("/datos_madre")
@login_required
def datos_madre():
    dmad = DatosMadre.query.filter_by(id=current_user.datos_madre_id).first()
    
    return render_template('ficha_dmad.html', dmad=dmad)

@services.route("/situacion_familiar")
@login_required
def situacion_familiar():
    sfam = SituacionFamiliar.query.filter_by(id=current_user.situacion_familiar_id).first()
    
    return render_template('ficha_sfam.html', sfam=sfam)

# @services.route("/news")
# def news():
#     page = request.args.get('page', 1, type=int)
#     news_posts = NewsPost.query.order_by(NewsPost.date.desc()).paginate(page=page, per_page=5)
#     return render_template('news.html', news_posts=news_posts)

ServicioSocialFS/users/views.py
# users/views.py
from flask import render_template, url_for, flash, redirect, request, Blueprint
from flask_login import login_user, current_user, logout_user, login_required
from ServicioSocialFS import db
from ServicioSocialFS.models import User, Ingresantes, DatosPersonales
from ServicioSocialFS.users.forms import RegistrationForm, LoginForm_ingresante, LoginForm_administrativo, LoginForm_regular, UpdateUserForm
from ServicioSocialFS.users.picture_handler import add_profile_pic

users = Blueprint('users', __name__)
# register

#### LOGIN ESTUDIANTE ######

@users.route('/login_ingresante', methods=['GET', 'POST'])
def login_ingresante():
    form = LoginForm_ingresante()
    if form.validate_on_submit():
        ingresante = Ingresantes.query.filter_by(dni=form.dni.data).first()
        user = DatosPersonales.query.filter_by(dni=form.dni.data).first()
        
        if user is None and ingresante is not None:
            print('ok1')
            next = request.args.get('next')
            if next == None or not next[0] == '/':
                next = url_for('services.form_ingresante')
                print("ok2")
            return redirect(next)
    return render_template('login_ingresante.html', form=form)


#### LOGIN REGULAR ######

@users.route('/login_regular', methods=['GET', 'POST'])
def login_regular():
    form = LoginForm_regular()
    if form.validate_on_submit():
        user = User.query.filter_by(codigo=form.codigo.data).first()
        
        if user.check_password(form.password.data) and user is not None:
            print('ok1')
            login_user(user)
            flash('Log in Success!')

            next = request.args.get('next')
            if next == None or not next[0] == '/':
                next = url_for('services.datos_personales')
                print("ok2")
            return redirect(next)
    return render_template('login_regular.html', form=form)

@users.route('/logout')
def logout():
    logout_user()
    return redirect(url_for("core.index"))

#### LOGIN ADMINISTRATIVO ######

@users.route('/login_administrativo', methods=['GET', 'POST'])
def login_administrativo():
    form = LoginForm_regular()
    if form.validate_on_submit():
        user = User.query.filter_by(codigo=form.codigo.data).first()
        
        if user.check_password(form.password.data) and user is not None:
            print('ok1')
            login_user(user)
            flash('Log in Success!')

            next = request.args.get('next')
            if next == None or not next[0] == '/':
                next = url_for('services.admin_page')
                print("ok2")
            return redirect(next)
    else:
        print('dont work')
    return render_template('login_administrativo.html', form=form)

########################################################


# @users.route('/register', methods=['GET', 'POST'])
# def register():
#     form = RegistrationForm()

#     if form.validate_on_submit():
#         user = User(email=form.email.data,
#                     username=form.username.data,
#                     password=form.password.data)
#         db.session.add(user)
#         db.session.commit()
#         flash('Thanks for registration!')
#         return redirect(url_for('users.login'))
#     return render_template('register.html', form=form)
# # login


# @users.route('/login', methods=['GET', 'POST'])
# def login():
#     form = LoginForm()
#     if form.validate_on_submit():
#         user = User.query.filter_by(email=form.email.data).first()
#         print(user)
#         print(form.password.data)
#         print(user.check_password(form.password.data))
#         if user.check_password(form.password.data) and user is not None:
#             print('ok1')
#             login_user(user)
#             flash('Log in Success!')

#             next = request.args.get('next')
#             if next == None or not next[0] == '/':
#                 next = url_for('core.index')
#                 print("ok2")
#             return redirect(next)
#     return render_template('login.html', form=form)


# # logout


# @users.route('/logout')
# def logout():
#     logout_user()
#     return redirect(url_for("core.index"))

# # account (update UserForm)


# @users.route('/account', methods=['GET', 'POST'])
# @login_required
# def account():
#     form = UpdateUserForm()
#     if form.validate_on_submit():
#         if form.picture.data:
#             username = current_user.username
#             pic = add_profile_pic(form.picture.data, username)
#             current_user.profile_image = pic

#         current_user.username = form.username.data
#         current_user.email = form.email.data
#         db.session.commit()
#         flash('User Account Updated')
#         return redirect(url_for('users.account'))
#     elif request.method == 'GET':
#         form.username.data = current_user.username
#         form.email.data = current_user.email

#     profile_image = url_for(
#         'static', filename='profile_pics/'+current_user.profile_image)
#     return render_template('account.html', profile_image=profile_image, form=form)

# # user's list of News Post


# @users.route("/<username>")
# def user_posts(username):
#     page = request.args.get('page', 1, type=int)
#     user = User.query.filter_by(username=username).first_or_404()
#     news_posts = NewsPost.query.filter_by(author=user).order_by(
#         NewsPost.date.desc()).paginate(page=page, per_page=5)

#     return render_template('user_news_posts.html', news_posts=news_posts, user=user)

ServicioSocialFS/templates/ficha_daca.html
{% extends "base_ficha.html" %}
{% block content %}

<div class="container-sm pb-3 flex-grow-1 d-flex flex-column flex-sm-row overflow-auto">
    <div class="row flex-grow-sm-1 flex-grow-0">
        <aside class="col-sm-3 flex-grow-sm-1 flex-shrink-1 flex-grow-0 sticky-top pb-sm-0 pb-3 fix">
            <div class="bg-light border rounded-3 p-1 h-100 sticky-top">
                <ul class="nav nav-pills flex-sm-column flex-row mb-auto justify-content-between text-truncate">
                    <li class="nav-item">
                        <a href="{{url_for('services.datos_personales')}}" class="nav-link px-2 text-truncate">
                            <i class="fas fa-id-card" data-toggle="tooltip" data-placement="top"
                                title="Datos Personales"></i>
                            <span class="d-none d-sm-inline">Datos Personales</span>
                        </a>
                    </li>
                    <li>
                        <a href="{{url_for('services.datos_procedencia')}}" class="nav-link px-2 text-truncate">
                            <i class="fa fa-earth-americas" data-toggle="tooltip" data-placement="top"
                                title="Datos de procedencia"></i>
                            <span class="d-none d-sm-inline">Datos de procedencia</span>
                        </a>
                    </li>
                    <li>
                        <a href="{{url_for('services.datos_residencia')}}" class="nav-link px-2 text-truncate">
                            <i class="fa-solid fa-house" data-toggle="tooltip" data-placement="top"
                                title="Datos de residencia"></i>
                            <span class="d-none d-sm-inline">Datos de residencia</span>
                        </a>
                    </li>
                    <li>
                        <a href="{{url_for('services.datos_academicos')}}" class="nav-link px-2 text-truncate">
                            <i class="fa-solid fa-book" data-toggle="tooltip" data-placement="top"
                                title="Datos academicos"></i>
                            <span class="d-none d-sm-inline">Datos academicos</span>
                        </a>
                    </li>
                    <li>
                        <a href="{{url_for('services.datos_padre')}}" class="nav-link px-2 text-truncate">
                            <i class="fas fa-user-tie" data-toggle="tooltip" data-placement="top"
                                title="Datos del padre"></i>
                            <span class="d-none d-sm-inline">Datos del padre</span>
                        </a>
                    </li>
                    <li>
                        <a href="{{url_for('services.datos_madre')}}" class="nav-link px-2 text-truncate">
                            <i class="fas fa-user-alt" data-toggle="tooltip" data-placement="top"
                                title="Datos de la madre"></i>
                            <span class="d-none d-sm-inline">Datos de la madre</span> </a>
                    </li>
                    <li>
                        <a href="{{url_for('services.situacion_familiar')}}" class="nav-link px-2 text-truncate">
                            <i class="fas fa-users" data-toggle="tooltip" data-placement="top"
                                title="Situación familiar"></i>
                            <span class="d-none d-sm-inline">Situación familiar</span> </a>
                    </li>
                    <hr class="my-1" />
                    <li>
                        <a href="#" class="nav-link px-2 text-truncate">
                            <i class="fa-solid fa-print" data-toggle="tooltip" data-placement="top"
                                title="Imprimir Constancia"></i>
                            <span class="d-none d-sm-inline">Imprimir Constancia</span> </a>
                    </li>
                </ul>
            </div>
        </aside>
        <main class="col overflow-auto h-100">
            <div class="bg-light border rounded-3 p-3">

                <h2>Datos Academicos</h2>
                <p class="desc">Información de datos académicos colegio donde estudio y más</p>
                <div class="row g-3">
                    <div class="col-sm-10">
                        <label for="" class="form-label">Colegio</label>
                        <input type="text" class="form-control" id="" placeholder="" value="{{daca.colegio}}"
                            readonly />
                    </div>

                    <div class="col-sm-4">
                        <label for="" class="form-label">Año que culmino sus estudios</label>
                        <input type="text" class="form-control" id="" placeholder=""
                            value="{{daca.ano_culminacion_estudio}}" readonly />
                    </div>
                    <div class="col-sm-5">
                        <label for="" class="form-label">Número de veces que postulo a la UNA</label>
                        <input type="text" class="form-control" id="" placeholder="" value="{{daca.num_postulacion}}"
                            readonly />
                    </div>
                    <div class="col-sm-10">
                        <label for="" class="form-label">Estudia adicionalmente la Escuela Profesional</label>
                        <input type="text" class="form-control" id="" placeholder="" value="{{daca.otra_carrera}}"
                            readonly />
                    </div>

                    <div class="col-sm-4">
                        <label for="" class="form-label">Tipo de preparación</label>
                        <input type="text" class="form-control" id="" placeholder="" value="{{daca.tipo_preparacion}}"
                            readonly />
                    </div>
                    <div class="col-sm-4">
                        <label for="" class="form-label">Escogio la UNA Puno por</label>
                        <input type="text" class="form-control" id="" placeholder="" value="{{daca.motivo_postulacion}}"
                            readonly />
                    </div>
                    <div class="col-sm-5">
                        <label for="" class="form-label">Escuela profesional a la que ingreso por</label>
                        <input type="text" class="form-control" id="" placeholder="" value="{{daca.escuela_motivo}}"
                            readonly />
                    </div>

                </div>

            </div>
        </main>
    </div>
</div>


{% endblock %}

ServicioSocialFS/templates/ficha_dpad.html
{% extends "base_ficha.html" %}
{% block content %}

<div class="container-sm pb-3 flex-grow-1 d-flex flex-column flex-sm-row overflow-auto">
    <div class="row flex-grow-sm-1 flex-grow-0">
        <aside class="col-sm-3 flex-grow-sm-1 flex-shrink-1 flex-grow-0 sticky-top pb-sm-0 pb-3 fix">
            <div class="bg-light border rounded-3 p-1 h-100 sticky-top">
                <ul class="nav nav-pills flex-sm-column flex-row mb-auto justify-content-between text-truncate">
                    <li class="nav-item">
                        <a href="{{url_for('services.datos_personales')}}" class="nav-link px-2 text-truncate">
                            <i class="fas fa-id-card" data-toggle="tooltip" data-placement="top"
                                title="Datos Personales"></i>
                            <span class="d-none d-sm-inline">Datos Personales</span>
                        </a>
                    </li>
                    <li>
                        <a href="{{url_for('services.datos_procedencia')}}" class="nav-link px-2 text-truncate">
                            <i class="fa fa-earth-americas" data-toggle="tooltip" data-placement="top"
                                title="Datos de procedencia"></i>
                            <span class="d-none d-sm-inline">Datos de procedencia</span>
                        </a>
                    </li>
                    <li>
                        <a href="{{url_for('services.datos_residencia')}}" class="nav-link px-2 text-truncate">
                            <i class="fa-solid fa-house" data-toggle="tooltip" data-placement="top"
                                title="Datos de residencia"></i>
                            <span class="d-none d-sm-inline">Datos de residencia</span>
                        </a>
                    </li>
                    <li>
                        <a href="{{url_for('services.datos_academicos')}}" class="nav-link px-2 text-truncate">
                            <i class="fa-solid fa-book" data-toggle="tooltip" data-placement="top"
                                title="Datos academicos"></i>
                            <span class="d-none d-sm-inline">Datos academicos</span>
                        </a>
                    </li>
                    <li>
                        <a href="{{url_for('services.datos_padre')}}" class="nav-link px-2 text-truncate">
                            <i class="fas fa-user-tie" data-toggle="tooltip" data-placement="top"
                                title="Datos del padre"></i>
                            <span class="d-none d-sm-inline">Datos del padre</span>
                        </a>
                    </li>
                    <li>
                        <a href="{{url_for('services.datos_madre')}}" class="nav-link px-2 text-truncate">
                            <i class="fas fa-user-alt" data-toggle="tooltip" data-placement="top"
                                title="Datos de la madre"></i>
                            <span class="d-none d-sm-inline">Datos de la madre</span> </a>
                    </li>
                    <li>
                        <a href="{{url_for('services.situacion_familiar')}}" class="nav-link px-2 text-truncate">
                            <i class="fas fa-users" data-toggle="tooltip" data-placement="top"
                                title="Situación familiar"></i>
                            <span class="d-none d-sm-inline">Situación familiar</span> </a>
                    </li>
                    <hr class="my-1" />
                    <li>
                        <a href="#" class="nav-link px-2 text-truncate">
                            <i class="fa-solid fa-print" data-toggle="tooltip" data-placement="top"
                                title="Imprimir Constancia"></i>
                            <span class="d-none d-sm-inline">Imprimir Constancia</span> </a>
                    </li>
                </ul>
            </div>
        </aside>
        <main class="col overflow-auto h-100">
            <div class="bg-light border rounded-3 p-3">

                <h2>Datos del Padre</h2>
                <p class="desc">Información de los datos personales del Padre</p>
                <div class="row g-3">
                    <div class="col-sm-4">
                        <label for="" class="form-label">Apellido Paterno</label>
                        <input type="text" class="form-control" id="" placeholder="" value="{{dpad.apellido_pa}}"
                            readonly />
                    </div>

                    <div class="col-sm-4">
                        <label for="" class="form-label">Apellido Materno</label>
                        <input type="text" class="form-control" id="" placeholder="" value="{{dpad.apellido_ma}}"
                            readonly />
                    </div>
                    <div class="col-sm-4">
                        <label for="" class="form-label">Nombres</label>
                        <input type="text" class="form-control" id="" placeholder="" value="{{dpad.nombre}}" readonly />
                    </div>
                    <div class="col-sm-3">
                        <label for="" class="form-label">¿Esta vivo?</label>
                        <input type="text" class="form-control" id="" placeholder="" value="{{dpad.esta_vivo}}"
                            readonly />
                    </div>
                    <div class="col-sm-4">
                        <label for="" class="form-label">Estado civil del Padre</label>
                        <input type="text" class="form-control" id="" placeholder="" value="{{dpad.estado_civil}}"
                            readonly />
                    </div>
                    <div class="col-sm-4">
                        <label for="" class="form-label">Nivel de Instrucción del Padre</label>
                        <input type="text" class="form-control" id="" placeholder="" value="{{dpad.nivel_educacion}}"
                            readonly />
                    </div>
                    <div class="col-sm-4">
                        <label for="" class="form-label">Fecha de Nacimiento del Padre</label>
                        <input type="text" class="form-control" id="" placeholder="" value="{{dpad.fecha_nacimiento}}"
                            readonly />
                    </div>
                </div>
                <hr class="my-4" />
                <h4 class="mb-3">Lugar de Procedencia del Padre</h4>

                <div class="row g-3">
                    <div class="col-sm-3">
                        <label for="" class="form-label">Pais</label>
                        <input type="text" class="form-control" id="" placeholder="" value="{{dpad.pais}}" readonly />
                    </div>
                    <div class="col-sm-3">
                        <label for="" class="form-label">Departamento</label>
                        <input type="text" class="form-control" id="" placeholder="" value="{{dpad.departamento}}"
                            readonly />
                    </div>
                    <div class="col-sm-4">
                        <label for="" class="form-label">Provincia</label>
                        <input type="text" class="form-control" id="" placeholder="" value="{{dpad.provincia}}"
                            readonly />
                    </div>



                    <div class="col-sm-3">
                        <label for="" class="form-label">Distrito</label>
                        <input type="text" class="form-control" id="" placeholder="" value="{{dpad.distrito}}"
                            readonly />
                    </div>

                    <div class="col-sm-3">
                        <label for="" class="form-label">¿Vive en zona rural?</label>
                        <input type="text" class="form-control" id="" placeholder="" value="{{dpad.zona_rural}}"
                            readonly />
                    </div>
                    <div class="col-sm-3">
                        <label for="" class="form-label">¿Presenta alguna discapacidad para trabajar?</label>
                        <input type="text" class="form-control" id="" placeholder=""
                            value="{{dpad.discapacidad_trabajo}}" readonly />
                    </div>




                    <div class="col-sm-5">
                        <label for="" class="form-label">Ocupacion</label>
                        <input type="number" class="form-control" maxlength="9" id=""
                            placeholder="{{dpad.primera_ocupacion}}" readonly />
                    </div>
                    <div class="col-sm-5">
                        <label for="" class="form-label">Segunda Ocupacion</label>
                        <input type="number" class="form-control" maxlength="9" id=""
                            placeholder="{{dpad.segunda_ocupacion}}" readonly />
                    </div>
                    <div class="col-sm-5">
                        <label for="" class="form-label">Ingresos del Padre (S/.)</label>
                        <input type="number" class="form-control" maxlength="9" id="" placeholder="{{dpad.ingresos}}"
                            readonly />
                    </div>
                </div>
            </div>
        </main>
    </div>
</div>


{% endblock %}